#!/bin/sh
set -e

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
	set -- apache2-foreground "$@"
fi

chmod 777 /var/lib/redis
chmod 777 /var/www

service redis-server start

exec "$@"